apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
spec:
  capacity: 
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs1
  nfs:
    path: /shared
    server: 211.183.3.99