---
apiVersion: v1
kind: Namespace
metadata:
  name: aws9
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deploy
  namespace: aws9
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db   #pod에 지정된 label과 동일해야
  template:    #여기부터 아래 내용 pod
    metadata:
      labels:
        app: db #위의 matchLabels와 맞춤
    spec:       #이 아래내용은 container
      containers:
      - name: mariadb-ctn
        image: mariadb:10.4
        env:
        - name: MARIADB_ROOT_PASSWORD
          value: test1234
        ports:
        - containerPort: 3306
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Equal
        value: ""
        effect: NoSchedule
      nodeSelector:
        kubernetes.io/hostname: master
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-svc
  namespace: aws9
spec:
  type: LoadBalancer
  selector:     #해당 LB로 접속하면 아래의 Label이 있는 pod로 포워딩
    app: db
  ports:
    - protocol: TCP
      port: 3306    #lb
      targetPort: 3306  #pod의 포트
      #나머지 ( clusterip, nodeport는 자동 할당 )