---
{{- range $app := .Values.apps }}
{{- with $ -}}
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ $app }}-deploy
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ $app }}
  template:
    metadata:
      labels:
        app: {{ $app }}
    spec:
      containers:
      - name: {{ $app }}-ctn
        image: {{ .Values.repo }}:{{ $app }}
        imagePullPolicy: Always
        ports:
          - containerPort: 80
        resources:
          requests:
            cpu: "{{ .Values.resources.cpuRequests }}"
          limits:
            cpu: "{{ .Values.resources.cpuLimits }}"
{{- end }}
---
{{- end }}