---
{{- range $app:=.Values.apps }}
{{- with $ -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $app }}-svc
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ $app }}
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
{{- end }}
---
{{- end }}