---
{{- range $app := .Values.apps }}
{{- with $ -}}
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ $app }}-deploy
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ $app }}
  template:
    metadata:
      labels:
        app: {{ $app }}
    spec:
      containers:
      - name: {{ $app }}-ctn
        image: kuzwolka/aws9:{{ $app }}
        ports:
          - containerPort: 80
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "200m"
{{- end }}
---
{{- end }}