apiVersion: v1
kind: Pod
metadata:
  name: "mypod"
  namespace: default
  labels:
    app: "MYAPP"
spec:
  containers:
  - name: myctn
    image: nginx
    ports:
    - containerPort:  80
  nodeName: node2