[project]
name = "event-planner"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "beanie==1.13.1",
    "fastapi>=0.115.14",
    "pydantic[email]>=2.11.7",
    "pymongo==4.3.3",
    "uvicorn>=0.35.0",
]
