[project]
name = "pyfastlab"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.115.14",
    "gunicorn>=23.0.0",
    "jinja2>=3.1.6",
    "pydantic>=2.11.7",
    "uvicorn>=0.35.0",
]
